/**
 * Utility for generating song type labels with Roman numerals
 * when multiple songs of the same type exist in an event.
 * 
 * Example: If an event has 2 "Comunhão" songs, they become "Comunhão I" and "Comunhão II"
 */

const ROMAN_NUMERALS = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'];

export interface SongWithType {
  id: string;
  type: string;
  [key: string]: any;
}

export interface TypeLabelMap {
  [songId: string]: string;
}

/**
 * Generates a map of song IDs to their display labels with Roman numerals.
 * Songs are processed in order, so the first occurrence gets "I", second gets "II", etc.
 * 
 * @param songs - Array of songs with their types, in display order
 * @param typeLabels - Map of type slugs to their display names (e.g., { comunhao: 'Comunhão' })
 * @returns Map of song IDs to their formatted labels
 */
export function generateSongTypeLabelsWithNumerals(
  songs: SongWithType[],
  typeLabels: Record<string, string>
): TypeLabelMap {
  // First pass: count occurrences of each type
  const typeCounts: Record<string, number> = {};
  songs.forEach((song) => {
    const type = song.type || 'outro';
    typeCounts[type] = (typeCounts[type] || 0) + 1;
  });

  // Second pass: assign labels with numerals where needed
  const typeCurrentIndex: Record<string, number> = {};
  const labelMap: TypeLabelMap = {};

  songs.forEach((song) => {
    const type = song.type || 'outro';
    const baseLabel = typeLabels[type] || type || 'Outro';
    
    if (typeCounts[type] > 1) {
      // Multiple songs of this type - add Roman numeral
      const index = typeCurrentIndex[type] || 0;
      const numeral = ROMAN_NUMERALS[index] || String(index + 1);
      labelMap[song.id] = `${baseLabel} ${numeral}`;
      typeCurrentIndex[type] = index + 1;
    } else {
      // Single song of this type - no numeral needed
      labelMap[song.id] = baseLabel;
    }
  });

  return labelMap;
}

/**
 * Gets the display label for a specific song, with Roman numeral if applicable.
 * 
 * @param songId - The song's ID
 * @param labelMap - The label map generated by generateSongTypeLabelsWithNumerals
 * @param fallback - Fallback label if song is not in the map
 * @returns The formatted label
 */
export function getSongTypeLabel(
  songId: string,
  labelMap: TypeLabelMap,
  fallback: string = 'Música'
): string {
  return labelMap[songId] || fallback;
}
